// 100 cute names + 100 motivational/love/support lines = 200 unique bubbles.

export const cuteNames: string[] = [
  "my qtyy paan masala",
  "sikhuuu",
  "babuuu",
  "shikharr bbyy",
  "mahh lovv",
  "baby",
  "qtyy",
  "shikharrr",
  "jii bby",
  "lysmm bby",
  "mwahhh",
  "honeyy",
  "sugarr plum",
  "cutiee pie",
  "my sunshinee",
  "love bugg",
  "sweet pea",
  "my prince",
  "cuddle bugg",
  "snuggle muffin",
  "my teddy",
  "jaan",
  "meri jaan",
  "shonaa",
  "golu molu",
  "chweetu",
  "buttercup",
  "honey bee",
  "my darling",
  "sweetheart",
  "angel face",
  "my everything",
  "boo bear",
  "cuddle bear",
  "my rockstar",
  "champ",
  "hero bby",
  "my king",
  "prince charming",
  "dreamboat",
  "handsome",
  "my heartbeat",
  "sweetuu",
  "laddu",
  "gudduu",
  "chotu",
  "pyaaru",
  "dilbar",
  "sanam",
  "mahiya",
  "my soulmate",
  "twinkle",
  "starboy",
  "moonpie",
  "sugar bear",
  "cookie",
  "muffin",
  "cupcake",
  "marshmallow",
  "jellybean",
  "peaches",
  "honeybun",
  "sweetcheeks",
  "lovey dovey",
  "my precious",
  "gem stone",
  "diamond bby",
  "my universe",
  "my galaxy",
  "starlight",
  "sunflower",
  "rosebud",
  "my petal",
  "sweet nothing",
  "cutie patootie",
  "pookie",
  "poooh bear",
  "my baby boy",
  "shikhu babu",
  "bubba",
  "my joy",
  "smiley",
  "giggles",
  "my treasure",
  "goldie",
  "sparkle",
  "my wish",
  "lucky charm",
  "my magic",
  "wonderboy",
  "dreamy",
  "cuddles",
  "hugsy",
  "kissy bby",
  "my forever",
  "bestest bby",
  "my cutie",
  "shikharu",
  "my lovee",
  "meri duniya",
  "my heart",
];

export const motivationalLines: string[] = [
  "you got this, always.",
  "i believe in you.",
  "you're never alone.",
  "i'm right here with you.",
  "you make me so proud.",
  "one step at a time.",
  "you are enough.",
  "keep going, my love.",
  "your smile fixes everything.",
  "i'm cheering for you.",
  "you're stronger than you know.",
  "every day with you counts.",
  "you can do hard things.",
  "i'm your biggest fan.",
  "breathe, i'm here.",
  "you shine so bright.",
  "the world needs your light.",
  "you're doing amazing.",
  "rest, then rise again.",
  "i'm proud of how far you've come.",
  "you're my safe place.",
  "we face it together.",
  "your heart is gold.",
  "you inspire me daily.",
  "tough days pass, i stay.",
  "you're worth every bit.",
  "keep that beautiful head up.",
  "i've got your back.",
  "you make hard look easy.",
  "small steps still count.",
  "you're allowed to slow down.",
  "i love your kind heart.",
  "you turn my day brighter.",
  "you're braver than you feel.",
  "i'm so lucky to have you.",
  "you deserve good things.",
  "keep dreaming big, love.",
  "your effort matters.",
  "you're growing every day.",
  "i see how hard you try.",
  "you never have to pretend.",
  "your feelings are valid.",
  "you're my favorite person.",
  "the storm won't last.",
  "you carry so much strength.",
  "i'm proud to be yours.",
  "you light up my world.",
  "you're doing better than you think.",
  "let me hold your worries.",
  "you're my whole heart.",
  "hard now, worth it later.",
  "you always find a way.",
  "i adore everything about you.",
  "your kindness changes people.",
  "keep believing in yourself.",
  "you make life sweeter.",
  "you're my calm and my chaos.",
  "i'll always choose you.",
  "you're capable of so much.",
  "one bad day isn't your story.",
  "you're my home.",
  "you make me feel safe.",
  "your dreams are valid.",
  "i'm here through it all.",
  "you're a whole vibe.",
  "keep shining, cutie.",
  "you handle life so well.",
  "you're my peace.",
  "never doubt your worth.",
  "you're my happy thought.",
  "you deserve rest and love.",
  "you're doing your best, always.",
  "i'm rooting for you daily.",
  "your smile is my favorite.",
  "you're stronger every day.",
  "the future looks good on you.",
  "i love your dreams.",
  "you're my greatest blessing.",
  "keep your heart soft.",
  "you're never too much for me.",
  "i'll walk with you always.",
  "you're my forever person.",
  "you make me want to be better.",
  "your love feels like home.",
  "you're brave for showing up.",
  "you're my reason to smile.",
  "keep pushing, my hero.",
  "you're a masterpiece.",
  "i believe in your dreams.",
  "you're my everything, truly.",
  "rest is not giving up.",
  "you're worth celebrating.",
  "your best is always enough.",
  "i'm proud of you today.",
  "you make ordinary magical.",
  "you're my favorite hello.",
  "keep going, i'm right beside you.",
  "you're loved beyond words.",
  "you're gonna be okay, promise.",
  "you and me, always.",
];
